### ISSUE TITLE
Run rubocop and yard in `rake default`

### ISSUE THREAD

**Issue by JelF** [0exp/symbiont-ruby#4]
1. Travis should use rake default.
  Motivation is simple: you can run `rake` before push and check would it pass.
1. Rake default should call rubocop.
  Rubocop should not fail in master. 
  See https://github.com/bbatsov/rubocop/blob/master/Rakefile as example.
1. Yard coverage check is welcome in `rake default`.
  If you wish something to be guarantied in master (i.e. full doc coverage), it is a good idea to add check.
  As example you can check my own Rakefile https://github.com/umbrellio/verifly/blob/3262164b9ee9fa6b4fc6d742fbf860202f537489/Rakefile#L29

**Comment by 0exp** [comment]
Yes, you right. PR is coming.
